# Generated by Django 2.1.3 on 2018-12-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteEditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
